name: "Set up postgres (windows)"
description: "Set up postgres service on windows vm for dbt integration tests"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # The Windows runner has some PostgreSQL environment variables set
        # that may confuse users since they may be irrelevant to the
        # PostgreSQL server we're using. Since GitHub actions does not
        # support unsetting environment variables, the best we can do is to
        # clear their values in order to indicate they must not be used.
        # for name in "PGROOT" "PGDATA" "PGBIN" "PGUSER" "PGPASSWORD"; do
        #   echo "$name=" >> $GITHUB_ENV
        # done


        choco upgrade postgresql \
          --params "/Password:password" \
          --ia "--enable-components server,commandlinetools --extract-only 1" \
          --no-progress

        # PG_BINDIR=$("$PROGRAMFILES/PostgreSQL/16/bin/pg_config.exe" --bindir)
        # PG_LIBDIR=$("$PROGRAMFILES/PostgreSQL/16/bin/pg_config.exe" --libdir)
    - shell: pwsh
      run: |
        $pgService = Get-Service -Name postgresql*
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
        $env:Path += ";$env:PGBIN"
        bash ${{ github.action_path }}/setup_db.sh
