# **what?**
# Nightly releases to GitHub and PyPI. This workflow produces the following outcome:
# - generate and validate data for night release (commit SHA, version number, release branch);
# - pass data to release workflow;
# - night release will be pushed to GitHub as a draft release;
# - night build will be pushed to test PyPI;
#
# **why?**
# Ensure an automated and tested release process for nightly builds
#
# **when?**
# This workflow runs on schedule or can be run manually on demand.


name: TESTING TEAM MEMBERSHIP

on:
  workflow_dispatch: # for manual triggering

defaults:
  run:
    shell: bash

permissions: write-all
  # contents: read # reads from the repository to get team membership

jobs:
  determine-team-membership:
    name: "Determine team membership"
    uses: dbt-labs/actions/.github/workflows/determine-team-membership.yml@er/repo-scope
    with:
      github_team: 'core'

    secrets: inherit
